s = 'AGATTATACAAAAAAGTGGGGCATGATTGTCATAGTGGATATGGGTCCACTAGGGCTGCACCGCATCGATACCTGCATGCATTCCCATTACGGAGGGTATAGGGACGCGCGACCGAGAGAGAGTCGAATAATCCGGTTGCCTCAGTACCGAATGACTTGGCTATAACTCGCGAGCCGACTATCTGCTTGGTAAATCCTGTAATTGCCATGACACTATGTTGCCACTGACCAAGCTTCAAGAAATGGCCCTGATCTTTTAGATACCGAAGGCCGGGATACCCCCAGGCCACATTAACGGATATCCCTTAAACCGTAGACCGCGACAAGCCCCCTTGTGTCCATTCTATCTAAGGCGTAACGAAATGTCGAGTCGACCTGTTACTGAAGACCGCAACTTTCTTATAATGTGGAAAATTGTCCGGCTTCTGACACAAGTTCGTTTACTAAATTAGTGGGAAGTTTACCATGTACTGCTCGTAAGCAGGTCCTACGTCCCCTAGATAGCGTCGTTCGCCGAACCATGAGTAGAAGAGCCATATTAAAATGATTAGACCATATGGGTGTGTCACACTAACTGGTTTATCATTTTGGAGCTGTCATTCCCGTATCTTTGGGAGATGTTCCGTACCGTACTAACTAATCATTTCCGGATGAAGTACCTAGGTACTTCACCCTATTCTGAGCGTCGCGGTCAATATATTAGACCCCCGTACACGCGCCAGCGCGAATTCTCAAAGTAAGACAGCCTTGGGAAGAAGTATCCCCCACCTTAGTCCTATATGGCCGAATGAATCTTATCGCTGCCAACGGGTTTACTTTGGCCAGATTAGTTCAGGAGATCTCCCCAATGGGCTCTCGTTGAAAGCGAGGTATTGCGTTTTGCGTGCTGATTATCAGATCCTCCGTAATTGGAGCGTAAAGGGTAGTCCAGGCGCAGATGGATCTTGGAATCAATTATAACTG'

RevS = s[::-1]
new = ''
for i in RevS:
    if i == 'A':
        new += 'T'
    elif i == 'T':
        new += 'A'
    elif i == 'G':
        new += 'C'
    elif i == 'C':
        new += 'G'

print(new)